import {
  Activity,
  AlarmClock,
  Apple,
  Award,
  BarChart,
  Bed,
  Bike,
  BookOpen,
  BrainCircuit,
  Briefcase,
  Calendar,
  Camera,
  Car,
  CheckCircle,
  Clipboard,
  Code,
  Coffee,
  CreditCard,
  DollarSign,
  Dumbbell,
  Film,
  Flag,
  Gift,
  GlassWater,
  Globe,
  Heart,
  Home,
  Image,
  Leaf,
  MapPin,
  Moon,
  Music,
  PenSquare,
  Phone,
  Plane,
  Repeat,
  Rocket,
  Settings,
  Smile,
  Sparkles,
  Speaker,
  Star,
  Sunrise,
  Sun,
  Target,
  Users,
  Video,
  Wallet,
  Watch,
  Wind,
  Zap,
} from 'lucide-react';

export const habitIcons = {
  Activity: Activity,
  AlarmClock: AlarmClock,
  Apple: Apple,
  Award: Award,
  BarChart: BarChart,
  Bed: Bed,
  Bike: Bike,
  BookOpen: BookOpen,
  BrainCircuit: BrainCircuit,
  Briefcase: Briefcase,
  Calendar: Calendar,
  Camera: Camera,
  Car: Car,
  CheckCircle: CheckCircle,
  Clipboard: Clipboard,
  Code: Code,
  Coffee: Coffee,
  CreditCard: CreditCard,
  DollarSign: DollarSign,
  Dumbbell: Dumbbell,
  Film: Film,
  Flag: Flag,
  Gift: Gift,
  GlassWater: GlassWater,
  Globe: Globe,
  Heart: Heart,
  Home: Home,
  Image: Image,
  Leaf: Leaf,
  MapPin: MapPin,
  Moon: Moon,
  Music: Music,
  PenSquare: PenSquare,
  Phone: Phone,
  Plane: Plane,
  Repeat: Repeat,
  Rocket: Rocket,
  Settings: Settings,
  Smile: Smile,
  Sparkles: Sparkles,
  Speaker: Speaker,
  Star: Star,
  Sunrise: Sunrise,
  Sun: Sun,
  Target: Target,
  Users: Users,
  Video: Video,
  Wallet: Wallet,
  Watch: Watch,
  Wind: Wind,
  Zap: Zap,
};

export type HabitIcon = keyof typeof habitIcons;

export const habitIconNames = Object.keys(habitIcons) as HabitIcon[];
