
import { User, Medal, Trophy, Star, Award } from 'lucide-react';

export const leaderboardUsers = [
  {
    id: 'user-1',
    name: 'Alex',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Alex',
    completions: 184,
    rank: 1,
    rankIcon: Medal,
    rankColor: 'text-amber-400',
  },
  {
    id: 'user-2',
    name: 'Sarah',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Sarah',
    completions: 172,
    rank: 2,
    rankIcon: Trophy,
    rankColor: 'text-slate-400',
  },
  {
    id: 'user-3',
    name: 'Mike',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Mike',
    completions: 165,
    rank: 3,
    rankIcon: Award,
    rankColor: 'text-amber-600',
  },
  {
    id: 'user-4',
    name: 'Jen',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Jen',
    completions: 158,
    rank: 4,
    rankIcon: Star,
    rankColor: 'text-muted-foreground',
  },
    {
    id: 'user-5',
    name: 'David',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=David',
    completions: 140,
    rank: 5,
    rankIcon: User,
    rankColor: 'text-muted-foreground',
  },
];


export const topHabits = [
    {
        id: 'habit-101',
        name: 'Daily Morning Run',
        streak: 128,
        user: 'Emily',
        userAvatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Emily',
        rank: 1,
        rankIcon: Medal,
        rankColor: 'text-amber-400',
    },
    {
        id: 'habit-102',
        name: 'Read 20 pages',
        streak: 115,
        user: 'Chris',
        userAvatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Chris',
        rank: 2,
        rankIcon: Trophy,
        rankColor: 'text-slate-400',
    },
    {
        id: 'habit-103',
        name: 'Code for 1 hour',
        streak: 98,
        user: 'Liam',
        userAvatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Liam',
        rank: 3,
        rankIcon: Award,
        rankColor: 'text-amber-600',
    },
    {
        id: 'habit-104',
        name: 'No Sugar',
        streak: 95,
        user: 'Olivia',
        userAvatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Olivia',
        rank: 4,
        rankIcon: Star,
        rankColor: 'text-muted-foreground',
    },
    {
        id: 'habit-105',
        name: 'Meditate',
        streak: 80,
        user: 'Noah',
        userAvatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Noah',
        rank: 5,
        rankIcon: User,
        rankColor: 'text-muted-foreground',
    }
]

export const timelineEvents = [
  {
    id: 'event-1',
    type: 'post',
    user: 'Sarah',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Sarah',
    timestamp: '2h ago',
    content: 'Just hit my 30-day streak for morning workouts! Feeling stronger than ever. Consistency is key! 💪',
    likes: 15,
    comments: [
      { id: 'c1', user: 'Alex', avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Alex', content: 'Awesome job, Sarah!' },
      { id: 'c2', user: 'Mike', avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Mike', content: 'Inspiring!' },
    ],
  },
  {
    id: 'event-2',
    type: 'habitCompletion',
    user: 'Alex',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Alex',
    timestamp: '3h ago',
    habitName: 'Read for 15 minutes',
  },
  {
    id: 'event-3',
    type: 'habitCompletion',
    user: 'Jen',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Jen',
    timestamp: '5h ago',
    habitName: 'Drink 8 glasses of water',
  },
  {
    id: 'event-4',
    type: 'post',
    user: 'Mike',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Mike',
    timestamp: '1d ago',
    content: 'Has anyone tried meditation for improving focus? I\'m starting a new 5-minute daily meditation habit today. Wish me luck!',
    likes: 8,
    comments: [
      { id: 'c3', user: 'Sarah', avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Sarah', content: 'It helps a lot! Stick with it.' },
    ],
  },
  {
    id: 'event-5',
    type: 'habitCompletion',
    user: 'David',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=David',
    timestamp: '1d ago',
    habitName: 'Eat a healthy breakfast',
  },
];
